apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k10-app-config-view 
rules:
- apiGroups:
  - config.kio.kasten.io
  resources:
  - profiles
  verbs:
  - get
  - list
- apiGroups:
  - config.kio.kasten.io
  resources:
  - policypresets
  - transformsets
  verbs:
  - '*'
- apiGroups:
  - reporting.kio.kasten.io
  - repositories.kio.kasten.io
  resources:
  - '*'
  verbs:
  - '*'
