apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k10-rbac-access 
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - list
  - get
  - create
  - update
  - delete
